image: dotnet/core/runtime:2.2

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - sudo apt-get install curl python-software-properties
          - curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
          - apt-get install nodejs
          - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
          - export PATH=$HOME/.yarn/bin:$PATH
          - yarn
          - npm run build
          - npm run start