image: mcr.microsoft.com/dotnet/core/runtime:2.2

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - apt-get install -y curl software-properties-common
          - curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
          - apt-get install -y nodejs
          - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
          - export PATH=$HOME/.yarn/bin:$PATH
          - yarn
          - npm run build
          - npm run start