image: node:latest

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
          - export PATH=$HOME/.yarn/bin:$PATH
          - yarn
          - npm run build
          - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
          - dpkg -i packages-microsoft-prod.deb
          - add-apt-repository universe
          - apt-get install apt-transport-https
          - apt-get update
          - apt-get install aspnetcore-runtime-2.2